apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: front
          image: azza177/frontend:latest
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: app-configmap